apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second-server
  template:
    metadata:
      labels:
        app: second-server
    spec:
      containers:
        - name: second-server-pod
          image: mohamedsaafan/second-server
