apiVersion: v1
kind: Service
metadata:
  name: second-server-service
spec:
  type: NodePort
  selector:
    app: second-server
  ports:
    - name: second-server-service
      protocol: TCP
      targetPort: 4000
      port: 4000
