apiVersion: v1
kind: Service
metadata:
  name: client-node-port-service
spec:
  type: NodePort
  selector:
    app: client
  ports:
    - name: client-service
      protocol: TCP
      port: 3000
      targetPort: 3000
