apiVersion: v1
kind: Service
metadata:
  name: server-node-service
spec:
  type: NodePort
  selector:
    app: server
  ports:
    - name: server
      protocol: TCP
      port: 8080
      targetPort: 8080
